# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Neigh', '0002_business_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
