# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-30 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neigh', '0004_auto_20181230_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighbourhood',
            options={},
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='email',
            field=models.EmailField(default='email', max_length=60),
        ),
    ]
