# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-31 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neigh', '0006_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighbourhood',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
